# Generated by Django 5.1.5 on 2025-01-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_dietcategory_checkout_dietplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='time',
        ),
        migrations.AddField(
            model_name='dietcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='file_or_image',
            field=models.FileField(blank=True, null=True, upload_to='diet_plans/'),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='diet_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='medicine.dietcategory'),
        ),
    ]
