# Generated by Django 5.1.5 on 2025-01-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_remove_dietplan_meal_remove_dietplan_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='file_or_image',
            field=models.FileField(upload_to='diet_plans/'),
        ),
    ]
